Environmental_Impact/urls.py
from django.contrib import admin
from django.urls import path, include
from impacts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('impacts.urls')),
]

impacts/urls.py
from django.urls import path
from . import views

app_name = 'impacts'

urlpatterns = [
    path('', views.home, name='home'),
    path('bills/', views.bills, name='bills'),
    path('veg/', views.veg, name='veg'),
]

impacts/models.py
from django.db import models

# Create your models here.

class Bills(models.Model):
    """
    creates a table in sqlite3 database
    automatically generates sql queries

    :params models.Model: what the class inherits from
    """
    name = models.CharField(max_length=55, blank=True)
    energy_supplier = models.CharField(max_length=55)
    num_of_people = models.IntegerField()
    heating_source = models.CharField(max_length=55)
    message = models.TextField(blank=True)
    impact = models.IntegerField()

    def __str__(self):
        """
        returns the class objects as a string

        :return: str 
        """
        return self.energy_supplier


class Veg(models.Model):
    """
    creates a table in sqlite3 database
    automatically generates sql queries

    :params models.Model: what the class inherits from
    """
    name = models.CharField(max_length=55, blank=True)
    current_meals = models.IntegerField()
    veggie_meals = models.CharField(max_length=55)
    co_impact = models.DecimalField(max_digits=10, decimal_places=3)
    water_impact = models.DecimalField(max_digits=10, decimal_places=3)
    waste_impact = models.DecimalField(max_digits=10, decimal_places=3)
    message = models.TextField(blank=True)

    def __str__(self):
        """
        returns the class objects as a string

        :return: str 
        """
        return self.veggie_meals

impacts/views.py
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist
from .models import Bills, Veg

# function based views
def home(request):
    """
    displays all pledges data fields

    :param request: HttpRequest object which contains the data 
    :return: renders the template home.html
    """
    bills = Bills.objects.all()
    vegs = Veg.objects.all()
    
    return render(request, 'impacts/home.html', {'bills': bills, 'vegs': vegs})


def bills(request):
    """
    displays the bills data fields

    :param request: HttpRequest object which contains the data 
    :return: renders the template home.html
    """
    if request.GET:
        if request.method == 'GET':
            energy = request.GET.get('energy')
            people = request.GET.get('people')
            people = int(float(people))
            heat = request.GET.get('heat')
            name = request.GET.get('name')
            message = request.GET.get('message')

            if energy == 'bog standard':
                a = 0.5
            else:
                a = 0

            if heat == 'electricity':
                b = 3
            else:
                b = 5

            impact = int(49 * a * b * people)

            try:
                bill = Bills.objects.create(name=name, energy_supplier=energy,
                    num_of_people=people, heating_source=heat, message=message, impact=impact)
                bill.save()
                
            except ObjectDoesNotExist:
                pass

            return render(request, 'impacts/bills.html', {'impact' : impact})

    else:
        return render(request, 'impacts/bills.html')


def veg(request):
    """
    displays the veg out data fields

    :param request: HttpRequest object which contains the data 
    :return: renders the template veg.html
    """
    if request.GET:
        if request.method == 'GET':
            current = request.GET.get('current')
            current = int(float(current))
            veggie = request.GET.get('veggie')
            name = request.GET.get('name')
            message = request.GET.get('message')

            if veggie == '0-5':
                a = 2.5
            else:
                a = 3

            co_impact = 0.884 * a * 8.7
            water_impact = 0.75 * current
            waste_impact = 0.2 * current * a

            try:
                veg_out = Veg.objects.create(name=name, current_meals=current,
                    veggie_meals=veggie, co_impact=co_impact, water_impact=water_impact,
                        waste_impact=waste_impact, message=message)
                veg_out.save()

            except ObjectDoesNotExist:
                pass

            return render(request, 'impacts/veg.html', {'co_impact': co_impact, 'waste_impact': waste_impact, 'water_impact': water_impact})

    return render(request, 'impacts/veg.html' )

impacts/templates/impacts/base.html
<!-- For templates inheritance -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- Reference stylesheet -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
  
  {%  block content %}
  {%  endblock %}

  <!-- jQuery and Optional JavaScript from Bootstrap -->
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</body>
</html>

impacts/templates/impacts/bills.html
{% extends "impacts/base.html" %}
{% load static %}

{% block content %}

<title>Bills</title>

  <div class="row header">
    <div class="col-sm-2" style="padding:10px">
      <img src="{% static 'img/wind_turbine.png' %}" class="col-sm-12" alt="Wind Turbine Image">
    </div>

    <div class=" col-sm-10 text-left">
      <h1 style="font-size:50px; font-weight:bold;">Clean Your Bills</h1>
      <p style="font-size:20px;">Switch to green energy supplier: it takes minutes and cost the same but the benefits will live on for years. It's quick and easy to switch and doesn't have to hurt your ban account</p>
      <p style="font-size:20px;">We'll send you more info and advice - including some of our top recommendations - once you've pledged.</p>
      <a style="color:white; font-size:20px; text-decoration:underline" href="{% url 'impacts:home' %}">More info / advice</a>
    </div>
  </div>

  <form action="{% url 'impacts:bills' %}" method="get">

    {%  csrf_token %}
    <div style="padding:25px;" class="row">
      <div class="col-sm-12 col-md-8">

        <label for="your_name">Name: </label>
        <input id="your_name" type="text" name="name" required>

        <p>Within the next two month, I pledge to switch from my current energy supplier - which is 
          <select style="padding:10px;" class="form-select rounded" aria-label="Default select example" name="energy">
            <option value="bog standard" selected>bog standard</option>
            <option value="a great green tariff">a great green tariff</option>
          </select> - to a green energy supplier.
          <input style="height:30px" type="number" name="people" min="1" required> people live in our home. My house is mainly heated by
          <select style="padding:10px;" class="form-select rounded" aria-label="Default select example" name="heat">
            <option selected>gas or oil</option>
            <option value="electricity">electricity</option>
          </select>
        </p>

        <p><b>Message: </b><br>Anything to say about your pledge? This will be publicly visible.<span style="float: right;">Characters left: <span id="rchars">255</span></span></p>
        <textarea name="message" class="form-control" type="text" id="textarea" value="" maxlength="255" required></textarea>

        <button class="btn btn-secondary" type="submit"><i class="fas fa-search" aria-hidden="true"></i>Pledge</button>

        <p style="padding-top: 10px;">Pledging for a specific friend or organisation? <a href"{% url 'impacts:home' %}">Find them first</a></p>
  </form>
    </div>

    <div style="border:1px solid black; height:auto;" class="col-sm-12 col-md-4 ">
      <h3 class="text-center"><b>Impacts</b></h3>
      <p>Saves</p>
      <p style="font-size:20px;" class="text-center"><b style="color:#FF8C00;" >{{ impact }}kg</b> of CO2</p>
      <p>Other impacts</p>
      <p style="font-size:20px;" class="text-center"><i class="fas fa-camera"></i>Pollution</p>
    </div>

  </div>

  <!-- To keep track of characters in message textarea -->
  <script>
    var maxLength = 255;
    $('textarea').keyup(function() {
      var textlen = maxLength - $(this).val().length;
      $('#rchars').text(textlen);
    });
  </script>


{% endblock %}

impacts/templates/impacts/home.html
{% extends "impacts/base.html" %}
{% load static %}

{% block content %}

<title>Home</title>

  <div class="row header">
    <div class="text-center col-sm-12">
      <h1 style="font-size:50px; font-weight:bold;">Home</h1>
    </div>
  </div>

  <div style="padding-left:10px;" class="row">
    <div class="col-sm-12">
      <h2><b>Select a Pledge</b></h2>
      <h3><a href="{% url 'impacts:bills' %}">Clean Your Bills</a></h3>
      <h3><a href="{% url 'impacts:veg' %}">Veg Out</a></h3>
    </div>
  </div>

  <div style="padding-left:10px;" class="row">
    <div class="col-sm-12 ">
      
      <h2><b>List of Pledges</b></h2>

      {% for bill in bills %}
        <p><b>Name: </b>{{ bill.name }}</p>
        <p><b>Pledge: </b>Switched from {{ bill.energy_supplier }}. Impact Made = {{ bill.impact }}</p>
        <p><b>Message: </b>{{ bill.message}}</p>
        <hr/>
      {% endfor %}

      {% for veg in vegs %}
        <p><b>Name: </b>{{ veg.name }}</p>
        <p><b>Pledge: </b>Switched from {{ veg.current_meals }} meaty meals to {{ veg.veggie_meals }} veg meals. Impacts Made => CO2 impact = {{ veg.co_impact }},
             Water impact = {{ veg.water_impact }}, Waste impact = {{ veg.waste_impact }}</p>
        <p><b>Message: </b>{{ veg.message}}</p>
        <hr/>
      {% endfor %}

    </div>
  </div>

{% endblock %}

impacts/templates/impacts/veg.html
{% extends "impacts/base.html" %}
{% load static %}

{% block content %}

<title>Veg</title>

  <div class="row header">
    <div class="col-sm-2" style="padding:10px">
      <img src="{% static 'img/vegan.png' %}" class="col-sm-12" alt="Vegan Image">
    </div>
    
    <div class=" col-sm-10 text-left">
      <h1 style="font-size:50px; font-weight:bold;">Veg Out</h1>
      <p style="font-size:20px;">Switch to Veggie Meals to create an impact on C02, Water and Waste Savings.</p>
      <p style="font-size:20px;">We'll send you more info and advice - including some of our top recommendations - once you've pledged.</p>
      <a style="color:white; font-size:20px; text-decoration:underline;" href="{% url 'impacts:home' %}">More info / advice</a>
    </div>
  </div>

  <form action="{% url 'impacts:veg' %}" method="get">

    {%  csrf_token %}
    <div style="padding:25px;" class="row">
      <div class="col-sm-12 col-md-8">

        <label for="your_name">Name: </label>
        <input id="your_name" type="text" name="name" required>
        
        <p>At the moment, I munch on 
          <input style="height:30px" type="number" name="current" min="1" required> meaty meals each week. For the next two months, I pledge to go veg for
          <select style="padding:10px;" class="form-select rounded" aria-label="Default select example" name="veggie">
            <option selected>0-5</option>
            <option value="6">6</option>
          </select> extra meals each week.
        </p>
        
        <p><b>Message:</b><br>Anything to say about your pledge? This will be publicly visible. <span style="float: right;">Characters left: <span id="rchars">255</span></span></p>


        <textarea name="message" class="form-control" type="text" id="textarea" value="" maxlength="255" required></textarea>
        <button class="btn btn-secondary" type="submit"><i class="fas fa-search"aria-hidden="true"></i>Pledge</button>

        <p style="padding-top: 10px;">Pledging for a specific friend or organisation? <a href"{% url 'impacts:home' %}">Find them first</a></p>
  </form>
    </div>

    <div style="border:1px solid black; height:auto;" class="col-sm-12 col-md-4 ">
      <h3 class="text-center"><b>Impacts</b></h3>
      <p>Saves</p>
      <p style="font-size:20px;" class="text-center"><b style="color:#FF8C00;" >{{ co_impact }}kg</b> of CO2</p>
      <p style="font-size:20px;" class="text-center"><b style="color:#FF8C00;" >{{ water_impact }}litre</b> of Water</p>
      <p style="font-size:20px;" class="text-center"><b style="color:#FF8C00;" >{{ waste_impact }}kg</b> of Waste</p>
      <p>Other impacts</p>
      <p style="font-size:20px;" class="text-center"><i class="fas fa-camera"></i>Pollution</p>
    </div>

  </div>

  <!-- To keep track of characters in message textarea -->
  <script>
    var maxLength = 255;
    $('textarea').keyup(function() {
      var textlen = maxLength - $(this).val().length;
      $('#rchars').text(textlen);
    });
  </script>


{% endblock %}